BF_PREFIX = "bf_prefix"
LOCK_PREFIX = "lock_prefix"
SET_PREFIX = "set_prefix"
DB_HASH_PREFIX = "db_prefix"

LOCK_UNIQUE_ID = "LOCK"
LOCK_ID_LEARN = "LEARN"

VECTOR_INDEX = "embeddings-idx"

EVENT_TOPIC = "event-topic"

MAX_RECOMMENDATIONS = 3
MAX_RESULTS = 5

LOCK_TIMEOUT = 30

TRAIN_TIMEOUT = 20
TRAIN_BATCH_SIZE = 64

MODEL_FILE_NAME = "model.pt"
MODEL_EMBEDDING_SIZE = 1536
MODEL_LEARNING_RATE = 1e-3