apiVersion: apps/v1
kind: Deployment
metadata:
  name: updaterecommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: updaterecommendations
  template:
    metadata:
      labels:
        service: updaterecommendations
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: updaterecommendations
          image: registry.digitalocean.com/recgencr/updaterecommendations:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: DATA_FILE
              value: "src/data.json"
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: openai_key
