apiVersion: apps/v1
kind: Deployment
metadata:
  name: updaterecommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: updaterecommendations
  template:
    metadata:
      labels:
        service: updaterecommendations
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: updaterecommendations
          image: registry.digitalocean.com/recgencr/updaterecommendations:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: REDIS_HOST
              value: "redis"
            - name: DATA_FILE
              value: "src/data.json"
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: openai_key
            - name: SPACES_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: spaces_access_key
            - name: SPACES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: spaces_secret_key
            - name: SPACES_ENDPOINT_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: spaces_endpoint_origin
            - name: SPACE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: space_name
