name: Build and deploy

on:
  pull_request:
    branches:
      - prod
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  build-submitevent:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        run: |
          docker login -u ${{ secrets.DIGITALOCEAN_USERNAME }} -p ${{ secrets.DIGITALOCEAN_TOKEN }} registry.digitalocean.com

      - name: Retrieve repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/src
          file: ${{ github.workspace }}/src/docker/submitevent.Dockerfile
          push: true
          tags: registry.digitalocean.com/recgencr/submitevent:latest

  build-updaterecommendations:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        run: |
          docker login -u ${{ secrets.DIGITALOCEAN_USERNAME }} -p ${{ secrets.DIGITALOCEAN_TOKEN }} registry.digitalocean.com

      - name: Retrieve repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/src
          file: ${{ github.workspace }}/src/docker/updaterecommendations.Dockerfile
          push: true
          tags: registry.digitalocean.com/recgencr/updaterecommendations:latest

  build-getrecommendations:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        run: |
          docker login -u ${{ secrets.DIGITALOCEAN_USERNAME }} -p ${{ secrets.DIGITALOCEAN_TOKEN }} registry.digitalocean.com

      - name: Retrieve repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/src
          file: ${{ github.workspace }}/src/docker/getrecommendations.Dockerfile
          push: true
          tags: registry.digitalocean.com/recgencr/getrecommendations:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      [build-submitevent, build-updaterecommendations, build-getrecommendations]
    steps:
      - name: Retrieve repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git for GitHub Actions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout deployment branch
        run: |
          git checkout prod
          git pull origin prod

      - name: Merge changes
        run: |
          git checkout prod-deployment
          git merge prod -m "Merge to deployment"

      - name: Push changes to deployment branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin prod-deployment
