name: Build images

on:
  pull_request:
    branches:
      - prod
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ github.workspace }}/src/submitevent
      #     file: ${{ github.workspace }}/src/submitevent/Dockerfile
      #     push: true
      #     tags: registry.digitalocean.com/recgensubmiteventcr:latest

      - name: Build and push
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

          ls ${{ github.workspace }}
          ls $GITHUB_WORKSPACE

          ls /

# https://github.com/actions/checkout/issues/785