name: Build images

on:
  pull_request:
    branches:
      - prod
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DigitalOcean Container Registry
      #   run: |
      #     docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_USERNAME }} -p ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Upload Docker credentials
        run: |
          mkdir -p ~/.docker
          echo ${{ secrets.DOCKER_CREDS }} > ~/.docker/config.json

      - name: Retrieve repo
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/src/submitevent
          file: ${{ github.workspace }}/src/submitevent/Dockerfile
          push: true
          tags: registry.digitalocean.com/recgensubmiteventcr:latest